export { init } from './commands/init'
export * from './constants'
export * from './types'
export { getPlatform, commandExists, isMacOS } from './utils/platform'
export * from './utils/installer'
export * from './utils/config'
export * from './utils/mcp'
export { importRecommendedEnv, importRecommendedPermissions, openSettingsJson } from './utils/simple-config'
export { cleanupPermissions, mergeAndCleanPermissions } from './utils/permission-cleaner'
export * from './utils/hooks'